import{a as L,S as w,i as u}from"./assets/vendor-CesYmgD5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const S="57437063-5e57d580090076aea82d313f5",q="https://pixabay.com/api/";async function f(e,o=1){return(await L.get(q,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}let v=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(e){const o=e.map(n=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${n.largeImageURL}">
        <img class="gallery-image" src="${n.webformatURL}" alt="${n.tags}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><span>${n.likes}</span></p>
        <p class="info-item"><b>Views</b><span>${n.views}</span></p>
        <p class="info-item"><b>Comments</b><span>${n.comments}</span></p>
        <p class="info-item"><b>Downloads</b><span>${n.downloads}</span></p>
      </div>
    </li>
  `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",o),v.refresh()}function P(){const e=document.querySelector(".gallery");e.innerHTML=""}function m(){document.querySelector(".loader").classList.remove("hidden")}function p(){document.querySelector(".loader").classList.add("hidden")}function h(){document.querySelector(".load-more-btn").classList.remove("hidden")}function l(){document.querySelector(".load-more-btn").classList.add("hidden")}function g(e){u.info({message:e,position:"topRight"})}function i(e){u.error({message:e,position:"topRight"})}const E=document.querySelector(".form"),M=document.querySelector(".load-more-btn");let d="",a=1;const b=15;E.addEventListener("submit",B);M.addEventListener("click",R);async function B(e){e.preventDefault();const o=e.currentTarget.elements["search-text"].value.trim();if(!o){i("Please enter a search query!");return}d=o,a=1,P(),l(),m();try{const s=await f(d,a);if(s.hits.length===0){i("Sorry, there are no images matching your search query. Please try again!");return}y(s.hits),s.totalHits>b?h():g("We're sorry, but you've reached the end of search results.")}catch{i("Something went wrong. Please try again later.")}finally{p()}}async function R(){a+=1,l(),m();try{const e=await f(d,a);y(e.hits),$();const o=Math.ceil(e.totalHits/b);a>=o?(l(),g("We're sorry, but you've reached the end of search results.")):h()}catch{i("Failed to load more images.")}finally{p()}}function $(){const e=document.querySelector(".gallery-item");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
